version: '3'
services:
  latest:
    image: httpdev${WORDPRESS_PHP}
    build:
      context: builds
      dockerfile: ${WORDPRESS_PHP}Dev.Dockerfile
    depends_on:
      - mariadb
    restart: always
    ports:
      - $HTTP_PORT:80
#      - $HTTPS_PORT:443
#      - $PHP_PORT:9000
    volumes:
      - "$APACHE_WWW_CONTENT:/var/www/html/"
      - "$APACHE_CONFIG:/etc/apache2/conf/"
      - "$PHP_CONFIG:/usr/local/etc/php/"
      - "$APACHE_PHP_LOGS:/var/log"
#      - "$APACHE_PRIVATE_KEY:/usr/local/apache2/conf/serverPriv.key"
#      - "$APACHE_PUBLIC_KEY:/usr/local/apache2/conf/serverPub.key"
      - "$SSH:/root/.ssh"
    environment:
      WORDPRESS_DB_HOST: "$MYSQL_HOSTNAME"
      WORDPRESS_DB_USER: "$MYSQL_USER_NAME"
      WORDPRESS_DB_PASSWORD: "$MYSQL_USER_PASSWORD"
      WORDPRESS_DB_NAME: "$MYSQL_DATABASE_NAME"
      WORDPRESS_TABLE_PREFIX: "$WP_TABLE_PREFIX"
#      WORDPRESS_DEBUG:
    networks:
      - front
      - back
  mariadb:
    hostname: "$MYSQL_HOSTNAME"
    image: "$MARIADB"
    restart: always
#    ports:
#      - $MYSQL_HOST_PORT:3306
    volumes:
      - "$MYSQL_CONFIG:/etc/mysql/"
      - "$MYSQL_DATA:/var/lib/mysql/"
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_USER: "$MYSQL_USER_NAME"
      MYSQL_PASSWORD: "$MYSQL_USER_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE_NAME"
    networks:
      - back

  redis:
    depends_on:
      - mariadb
    hostname: "$REDIS_HOSTNAME"
    image: "$REDIS"
    networks:
      - back

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
#    expose: 80
    environment:
      PMA_HOST: "$MYSQL_HOSTNAME"
      PMA_USER: "$MYSQL_USER_NAME"
      PMA_PASSWORD: "$MYSQL_USER_PASSWORD"
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    networks:
      - back

networks:
  front:
  back:
