version: '3'
services:

#  traefik:
#    image: "$TRAEFIK"
#    container_name: "traefik"
#    hostname: "$$TRAEFIK_HOSTNAME"
#    restart: always
#    command:
##      - "--providers.docker.exposedbydefault=true"
#      - "--log.level=DEBUG"
#      - "--providers.docker=true"
#      - "--providers.docker.network=frontend-docker-apache-php-mariabd"
#      - "--entrypoints.web.address=:80"
#      - "--entrypoints.phpmyadmin.address=:8000"
##      - "--entrypoints.entrypoints-https.address=:443"
##      - "--entrypoints.websecure.address=:443"
##      - "--entrypoints.entrypoints-http.address=:80"
##      - "--entrypoints.entrypoints-http.http.redirections.entryPoint.to=entrypoints-https"
##      - "--entrypoints.entrypoints-http.http.redirections.entryPoint.scheme=https"
##      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
##      - "--certificatesresolvers.myresolver.acme.email=ttvestee@gmail.com+dockertraefik"
##      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
##      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=entrypoints-http"
##     pour metrics avec prometheus et grafana : ( https://medium.com/platform-engineering/monitoring-traefik-with-grafana-1d037af5>
#      - '--entryPoints.metrics.address=:8082'
#      - '--providers.providersThrottleDuration=2s'
#      - '--accessLog.bufferingSize=0'
#      - '--api=true'
#      - '--api.dashboard=true'
#      - '--api.insecure=true'
#      - '--ping.entryPoint=web'
#      - '--metrics.prometheus=true'
#      - '--metrics.prometheus.addEntryPointsLabels=true'
#      - '--metrics.prometheus.addServicesLabels=true'
#      - '--metrics.prometheus.manualrouting=true'
#    ports:
#      - "$HTTP_PORT:80"
#      - "$HTTPS_PORT:443"
#      - "$TRAEFIK_METRICS_PORT:8082"
#      - "8000:8000"
#      - "$TRAEFIK_PORT:8080"
#    labels:
#      - "traefik.enable=false"
#    volumes:
##      - "$LETSENCRYPT:/letsencrypt"
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - type: bind
#        source: /var/run/docker.sock
#        target: /var/run/docker.sock
#        read_only: true
#    networks:
#      - frontend
#
  wordpress:
    image: $WORDPRESS
    restart: always
    ports:
      - $HTTP_PORT:80
#      - $HTTPS_PORT:443
      - $PHP_PORT:9000
    volumes:
      - "$APACHE_WWW_CONTENT:/var/www/html/"
      - "$APACHE_CONFIG:/etc/apache2/conf/"
      - "$PHP_CONFIG:/usr/local/etc/php/"
#Unsafe#      - $APACHE_PHP_LOGS:/var/logs
#Unsafe#      - $APACHE_PRIVATE_KEY:/usr/local/apache2/conf/
#      - $APACHE_PUBLIC_KEY:/usr/local/apache2/conf/

#    labels:
#      - traefik.http.routers.http.entrypoints=web
    environment:
      WORDPRESS_DB_HOST: "$MYSQL_HOSTNAME"
      WORDPRESS_DB_USER: "$MYSQL_USER_NAME"
      WORDPRESS_DB_PASSWORD: "$MYSQL_USER_PASSWORD"
      WORDPRESS_DB_NAME: "$MYSQL_DATABASE_NAME"
      WORDPRESS_TABLE_PREFIX: "$WP_TABLE_PREFIX"
#      WORDPRESS_AUTH_KEY: 
#      WORDPRESS_SECURE_AUTH_KEY:
#      WORDPRESS_LOGGED_IN_KEY:
#      WORDPRESS_NONCE_KEY:
#      WORDPRESS_AUTH_SALT:
#      WORDPRESS_SECURE_AUTH_SALT:
#      WORDPRESS_LOGGED_IN_SALT:
#      WORDPRESS_NONCE_SALT:
#      WORDPRESS_DEBUG:
  mariadb:
    hostname: "$MYSQL_HOSTNAME"
    image: "$MARIADB"
    restart: always
#    ports:
#      - $MYSQL_HOST_PORT:3306
    volumes:
      - "$MYSQL_CONFIG:/etc/mysql/"
      - "$MYSQL_DATA:/var/lib/mysql/"
    labels:
      - "traefik.enable=false"
#      - "traefik.http.routers.mariadb.rule=PathPrefix(`/`)"
#      - "traefik.http.routers.mariadb.rule=Host(`example.localhost`)"
#      - "traefik.http.services.mariadb.loadbalancer.server.port=3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_USER: "$MYSQL_USER_NAME"
      MYSQL_PASSWORD: "$MYSQL_USER_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE_NAME"

  redis:
    hostname: "$REDIS_HOSTNAME"
    image: "$REDIS"
    labels:
      - "traefik.enable=false"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'

#    expose: 80
#    labels:
#      - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/`)"
##      - "traefik.http.routers.apache-php.rule=Host(`wordpress.localhost`)"
##      - "traefik.http.services.frontend.loadbalancer.server.port=80"
##      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=8000"
##      - "traefik.http.routers.phpmyadmin.entrypoints=phpmyadmin"
##      - "traefik.port=8000"
##      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)
##      - "traefik.enable=false"
#      - traefik.enable=true
#      - traefik.http.routers.phpmyadmin.entrypoints=phpmyadmin
#      - traefik.http.routers.phpmyadmin.service=phpmyadmin
##      - traefik.http.services.phpmyadmin-service.loadbalancer.server.port=8000
    environment:
      PMA_HOST: "$MYSQL_HOSTNAME"
      PMA_USER: "$MYSQL_USER_NAME"
      PMA_PASSWORD: "$MYSQL_USER_PASSWORD"
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"


