version: '3'
services:
  apache:
    image: $HTTPD_VERVION
    restart: always
    networks:
      - apache-php-mariadb
    ports:
      - $HOST_HTTP_PORT:80
      - $HOST_HTTPS_PORT:443
    links:
      - mariadb
      - php-fpm
    volumes:
      - $WWW_CONTENT:/usr/local/apache2/htdocs/
      - $APACHE_CONFIG:/usr/local/apache2/conf/
#      - $APACHE_PRIVATE_KEY:/usr/local/apache2/conf/
#      - $APACHE_PUBLIC_KEY:/usr/local/apache2/conf/
    environment:
      - ALLOW_OVERRIDE=true

  php-fpm:
    image: $PHP_VERSION
    restart: always
    links:
      - apache
    networks:
      - apache-php-mariadb
    ports:
      - $PHP_PORT:9000
    volumes:
      - $PHP_CONFIG:/etc/php

  mariadb:
    image: $MARIADB_VERSION
    restart: always
    networks:
      - apache-php-mariadb
    ports:
      - $MYSQL_HOST_PORT:3306
    volumes:
      - $MYSQL_DATA:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER-NAME
      MYSQL_PASSWORD: $MYSQL_USER_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE_NAME


networks:
  apache-php-mariadb:
    driver: bridge
