version: '3'
services:
  apache-php:
    image: wordpress:6.0.2-php7.4-apache 
    restart: always
    networks:
      - apache-php-mariadb
    ports:
      - $HOST_HTTP_PORT:80
      - $HOST_HTTPS_PORT:443
#      - $PHP_PORT:9000
    volumes:
      - $APACHE_WWW_CONTENT:/var/www/html
      - $APACHE_CONFIG:/etc/apache2/conf/
      - $PHP_CONFIG:/usr/local/etc/php 
#      - $APACHE_PRIVATE_KEY:/usr/local/apache2/conf/
#      - $APACHE_PUBLIC_KEY:/usr/local/apache2/conf/
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: $MYSQL_USER-NAME
      WORDPRESS_DB_PASSWORD: $MYSQL_USER_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE_NAME
      WORDPRESS_TABLE_PREFIX: _wp
#      WORDPRESS_AUTH_KEY: 
#      WORDPRESS_SECURE_AUTH_KEY:
#      WORDPRESS_LOGGED_IN_KEY:
#      WORDPRESS_NONCE_KEY:
#      WORDPRESS_AUTH_SALT:
#      WORDPRESS_SECURE_AUTH_SALT:
#      WORDPRESS_LOGGED_IN_SALT:
#      WORDPRESS_NONCE_SALT:
#      WORDPRESS_DEBUG:



  mariadb:
    image: $MARIADB_VERSION
    restart: always
    networks:
      - apache-php-mariadb
    ports:
      - $MYSQL_HOST_PORT:3306
    volumes:
      - $MYSQL_CONFIG:/etc/mysql
      - $MYSQL_DATA:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER-NAME
      MYSQL_PASSWORD: $MYSQL_USER_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE_NAME


networks:
  apache-php-mariadb:
    driver: bridge
